// BudgetingApp.Models.Category.cs
// This file defines the Category model for the BudgetingApp.
// It includes properties for the category ID, name, and a collection of associated expense.


// Import necessary namespaces 

using System.Collections.Generic; // needed for using collections, like List<T>
using System.ComponentModel.DataAnnotations; // needed for validation and display attributes 

namespace BudgetingApp.Models 

{
    // This class represents a 'category' of expense (Like Food, Rent, Entertainment, Car Insurance, etc.)
    public class Category
    {
        // This is the primary key for the Category Table 
        // It is automatically generated by the database (Identity column)
        public int CategoryId { get; set; }

        // Naming the Expense Category.
        // This field is required. The user must enter a name for the category.
        // The [Display] attribute sets the label that appears in forms or tables.
        [Required(ErrorMessage = "Category name is required.")]
        [StringLength(120, ErrorMessage = "Category name cannot exceed 120 characters.")]
        [Display(Name = "Category Name")]

        public string Name { get; set; } = string.Empty;

        // The property holds the expense that belong to this category.
        // It's initialized to an empty list to avoid null reference exceptions.
        // This will allow for easy addition and removal of expense from the category.

        // This is a navigation property that allows us to access the expense associated with this category.
        // Relationship: One to Many (ie: One Category can have Many Expense)
        public ICollection<Expense> Expense { get; set; } = new List<Expense>(); 
    }
}