// Expense.cs
// This file defines the Expense model for the BudgetingApp application.
// An Expense represents a single expense, including its name, amount, date, and associated category.

// Import necessary namespaces 

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema; // to ref database 

namespace BudgetingApp.Models
{
    // This class represents a single Expense entry (e.g. $90 spent on gas)
    public class Expense
    {
        // Primary key for the Expense Table, identifies each unique expense and is generated by the database
        public int ExpenseId { get; set; }

        // Name of Expense. Required field, max length 120 characters
        [Required(ErrorMessage = "Expense Name is required.")]
        [Display(Name = "Expense Name")]
        public string Name { get; set; }

        // $$$ Dollar amount of the expense. Must be greater than 0. 
        // The [Range] attribute ensures the value is within a valid range. 
        [Required(ErrorMessage = "Expense Amount is Required.")]
        [Range(0.01, 500000.00, ErrorMessage = "Expense Value must be between $0.01 and $5 000 000.00")]
        public decimal Amount { get; set; }

        // Date the expense was incurred. Required field. 
        // The [DataType] attribute specifies that this field is a date, which helps with formatting in views, since it hints to ASP.NET to show a date picking thingy in the form
        [DataType(DataType.Date)]
        public DateTime Data { get; set; }

        // Insures each expense belongs to a category (like Food, Rent, Entertainment, etc.)
        // Foreign key relationship to Category table
        [Display(Name = "Category")]
        public int CategoryId { get; set; }

        // This is a navigation property that allows us to ACCESS the Category associated with this expense. 
        [ForeignKey("CategoryId")] // Tells database to use CategoryId as the foreign key
        public Category Category { get; set; }
    }
}